sudo: false
language: ruby
rvm:
  - 2.4.2
  - 2.2
install:
  - bundle install
script:
  - bundle exec jekyll build
  - bundle exec rake clean
  ##- bundle exec htmlproofer ./_site --only-4xx --check-favicon --check-html
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
addons:
  apt:
    packages:
    - libcurl4-openssl-dev # required to avoid SSL errors

